#!/bin/bash
# build_spike.sh -- build OPENMV_AE3 firmware WITH the bm_spike usermod.
#
# Mechanism (no openmv fork, no patch): openmv's modules/micropython.mk
# compiles every *.c in the tree's modules/ dir via SRC_USERMOD wildcard
# and the top Makefile passes USER_C_MODULES=$(TOP_DIR) to MicroPython.
# So: copy our sources + the vendored driver into <openmv>/modules/,
# run the standard build_ae3.sh, then remove the copies (trap'd).
#
# bm_adin2111.c is vendored for reference but NEVER copied/compiled: it is
# bm_core's NetworkDevice wrapper and needs bm_os -- and it defines its own
# HAL_RegisterCallback, which would collide with bm_spike_hal_mp.c.
#
# Usage: build_spike.sh [--openmv-dir DIR] [--hal mp|alif]
#                       [args passed through to build_ae3.sh]
#
# --hal picks the adi_hal.h implementation staged into the build (the two
# files define the same symbols, so exactly one is ever staged):
#   mp    (default) bite-1 baseline: machine.SPI-backed, polled, IRQ stubs
#   alif  bite-2:   bare-metal SPI0 FIFO-burst + real INT_N IRQ path

set -euo pipefail
cd "$(dirname "$0")"

OPENMV_DIR="${HOME}/openmv-dev/openmv"
NO_PROT=0
CLEAN=0
HAL=mp
PASSTHRU=()
while [ $# -gt 0 ]; do
    case "$1" in
        --openmv-dir) OPENMV_DIR="$2"; PASSTHRU+=("$1" "$2"); shift 2 ;;
        --no-prot)    NO_PROT=1; shift ;;
        --clean)      CLEAN=1; shift ;;
        --hal)        HAL="$2"; shift 2 ;;
        *)            PASSTHRU+=("$1"); shift ;;
    esac
done

case "$HAL" in
    mp)   HAL_SRC=src/bm_spike_hal_mp.c;   HAL_ALIF_DEF=0 ;;
    alif) HAL_SRC=src/bm_spike_hal_alif.c; HAL_ALIF_DEF=1 ;;
    *)    echo "FAIL: --hal must be mp or alif (got: ${HAL})" >&2; exit 1 ;;
esac

MOD_DIR="${OPENMV_DIR}/modules"
[ -d "${MOD_DIR}" ] || { echo "FAIL: ${MOD_DIR} not found -- clone via build_ae3.sh first" >&2; exit 1; }

# The stage/unstage dance defeats make's header dependency tracking (a
# staged header is deleted after every build), so config changes CAN reuse
# stale objects -- proven by a byte-identical bin after an adi_config.h
# edit. Use --clean when anything about the staged set changed.
if [ "$CLEAN" = "1" ]; then
    echo "cleaning ${OPENMV_DIR}/build"
    rm -rf "${OPENMV_DIR}/build"
fi

COPIED=()
cleanup() {
    for f in ${COPIED[@]+"${COPIED[@]}"}; do rm -f "$f"; done
}
trap cleanup EXIT

stage() {   # stage <src-path> <dst-basename>
    local dst="${MOD_DIR}/$2"
    [ -e "$dst" ] && { echo "FAIL: ${dst} already exists -- refusing to overwrite" >&2; exit 1; }
    cp "$1" "$dst"
    COPIED+=("$dst")
}

# Our sources carry their own #if !defined(CORE_M55_HE) guards. (Bite-1
# note said "HE cannot fit the spike"; D24 root-caused that to the docker
# per-core build-dir bug. The guards stay: the spike belongs on HP with
# the REPL and the P0-P5 pins.)
#
# The two HAL implementations define the same adi_hal.h symbols, so only
# the --hal choice is staged; the mod file reads the generated choice
# header to expose the matching Python API.
for f in src/*.c src/*.h; do
    case "$(basename "$f")" in
        bm_spike_hal_mp.c|bm_spike_hal_alif.c) continue ;;
    esac
    stage "$f" "$(basename "$f")"
done
stage "$HAL_SRC" "$(basename "$HAL_SRC")"

CHOICE="${MOD_DIR}/bm_spike_hal_choice.h"
[ -e "$CHOICE" ] && { echo "FAIL: ${CHOICE} already exists" >&2; exit 1; }
printf '// generated by build_spike.sh --hal %s\n#define BM_SPIKE_HAL_ALIF %d\n' \
    "$HAL" "$HAL_ALIF_DEF" > "$CHOICE"
COPIED+=("$CHOICE")
echo "NOTE: HAL = ${HAL} ($(basename "$HAL_SRC"))"

# Vendored driver: headers as-is; .c files stay BYTE-IDENTICAL but are
# staged as .inc (outside the modules/*.c wildcard) behind a generated
# HE-exclusion wrapper, so the vendored content is never edited.
# bm_adin2111.{c,h} excluded entirely (needs bm_os; defines its own HAL fn).
for f in vendor/adin2111/*.h; do
    case "$(basename "$f")" in
        bm_adin2111.h) continue ;;
        adi_config.h)
            if [ "$NO_PROT" = "1" ]; then
                # DELTA-QUANTIFICATION build (S9 bench finding: PROTE is not
                # settable on our ADIN1110, so the shipped protected config
                # can never work). One-define change, applied at stage time;
                # the vendored file itself stays byte-identical in the repo.
                dst="${MOD_DIR}/adi_config.h"
                [ -e "$dst" ] && { echo "FAIL: ${dst} exists" >&2; exit 1; }
                # The driver tests #if defined(CONFIG_SPI_PROT_EN) -- the
                # define must be REMOVED, not zeroed (a =0 build was
                # byte-identical; that sha comparison is the regression test).
                sed 's|#define CONFIG_SPI_PROT_EN  1|/* CONFIG_SPI_PROT_EN removed: PROTE unavailable on our ADIN1110 (S9 measurement) */|' "$f" > "$dst"
                if grep -q "define CONFIG_SPI_PROT_EN" "$dst"; then echo "FAIL: --no-prot sed missed" >&2; exit 1; fi
                COPIED+=("$dst")
                echo "NOTE: staged adi_config.h with CONFIG_SPI_PROT_EN=0 (--no-prot)"
                continue
            fi
            ;;
    esac
    stage "$f" "$(basename "$f")"
done
for f in vendor/adin2111/*.c; do
    base=$(basename "$f")
    case "$base" in bm_adin2111.c) continue ;; esac
    stage "$f" "${base%.c}.inc"
    wrapper="${MOD_DIR}/bmv_${base}"
    [ -e "$wrapper" ] && { echo "FAIL: ${wrapper} already exists" >&2; exit 1; }
    printf '// generated by build_spike.sh -- HE-core exclusion wrapper\n#if !defined(CORE_M55_HE)\n#include "%s"\n#endif\n' \
        "${base%.c}.inc" > "$wrapper"
    COPIED+=("$wrapper")
done
echo "staged ${#COPIED[@]} spike files into ${MOD_DIR}"

../openmv_build/build_ae3.sh ${PASSTHRU[@]+"${PASSTHRU[@]}"}

echo
echo "bm_spike build done. Flash via pi/ae3_flash (S7 ladder), then on the"
echo "REPL: import s9_oa_spike (or run firmware/bm_spike/s9_oa_spike.py)."
