#!/bin/bash
# build_spike.sh -- build OPENMV_AE3 firmware WITH the bm_spike usermod.
#
# Mechanism (no openmv fork, no patch): openmv's modules/micropython.mk
# compiles every *.c in the tree's modules/ dir via SRC_USERMOD wildcard
# and the top Makefile passes USER_C_MODULES=$(TOP_DIR) to MicroPython.
# So: copy our sources + the vendored driver into <openmv>/modules/,
# run the standard build_ae3.sh, then remove the copies (trap'd).
#
# bm_adin2111.c is vendored for reference but NEVER copied/compiled: it is
# bm_core's NetworkDevice wrapper and needs bm_os -- and it defines its own
# HAL_RegisterCallback, which would collide with bm_spike_hal_mp.c.
#
# Usage: build_spike.sh [--openmv-dir DIR] [args passed through to build_ae3.sh]

set -euo pipefail
cd "$(dirname "$0")"

OPENMV_DIR="${HOME}/openmv-dev/openmv"
PASSTHRU=()
while [ $# -gt 0 ]; do
    case "$1" in
        --openmv-dir) OPENMV_DIR="$2"; PASSTHRU+=("$1" "$2"); shift 2 ;;
        *)            PASSTHRU+=("$1"); shift ;;
    esac
done

MOD_DIR="${OPENMV_DIR}/modules"
[ -d "${MOD_DIR}" ] || { echo "FAIL: ${MOD_DIR} not found -- clone via build_ae3.sh first" >&2; exit 1; }

COPIED=()
cleanup() {
    for f in ${COPIED[@]+"${COPIED[@]}"}; do rm -f "$f"; done
}
trap cleanup EXIT

stage() {   # stage <src-path> <dst-basename>
    local dst="${MOD_DIR}/$2"
    [ -e "$dst" ] && { echo "FAIL: ${dst} already exists -- refusing to overwrite" >&2; exit 1; }
    cp "$1" "$dst"
    COPIED+=("$dst")
}

# Our sources carry their own #if !defined(CORE_M55_HE) guards (the HE
# image cannot fit the spike -- first build: FLASH_TEXT 154% on HE).
for f in src/*.c src/*.h; do
    stage "$f" "$(basename "$f")"
done

# Vendored driver: headers as-is; .c files stay BYTE-IDENTICAL but are
# staged as .inc (outside the modules/*.c wildcard) behind a generated
# HE-exclusion wrapper, so the vendored content is never edited.
# bm_adin2111.{c,h} excluded entirely (needs bm_os; defines its own HAL fn).
for f in vendor/adin2111/*.h; do
    case "$(basename "$f")" in bm_adin2111.h) continue ;; esac
    stage "$f" "$(basename "$f")"
done
for f in vendor/adin2111/*.c; do
    base=$(basename "$f")
    case "$base" in bm_adin2111.c) continue ;; esac
    stage "$f" "${base%.c}.inc"
    wrapper="${MOD_DIR}/bmv_${base}"
    [ -e "$wrapper" ] && { echo "FAIL: ${wrapper} already exists" >&2; exit 1; }
    printf '// generated by build_spike.sh -- HE-core exclusion wrapper\n#if !defined(CORE_M55_HE)\n#include "%s"\n#endif\n' \
        "${base%.c}.inc" > "$wrapper"
    COPIED+=("$wrapper")
done
echo "staged ${#COPIED[@]} spike files into ${MOD_DIR}"

../openmv_build/build_ae3.sh ${PASSTHRU[@]+"${PASSTHRU[@]}"}

echo
echo "bm_spike build done. Flash via pi/ae3_flash (S7 ladder), then on the"
echo "REPL: import s9_oa_spike (or run firmware/bm_spike/s9_oa_spike.py)."
